# Generated by Django 4.2.3 on 2023-07-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
